"""bookings

Revision ID: 1c2bfa9b3fb4
Revises: 9d3ca938961d
Create Date: 2023-07-29 15:29:11.219985

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1c2bfa9b3fb4'
down_revision = '9d3ca938961d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('room_id', sa.Integer(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('date_from', sa.Date(), nullable=False),
                    sa.Column('date_to', sa.Date(), nullable=False),
                    sa.Column('price', sa.Integer(), nullable=False),
                    sa.Column('total_cost', sa.Integer(), sa.Computed('(date_to - date_from) * price', ),
                              nullable=True),
                    sa.Column('total_days', sa.Integer(), sa.Computed('date_to - date_from', ), nullable=True),
                    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bookings')
    # ### end Alembic commands ###
